[versions]
dokka = "2.1.0"
spotless = "8.0.0"
gradleRIO = "2025.3.2"
junit = "6.0.1"
malefix = "2.4.0"

[libraries]
dokka-java = { group = "org.jetbrains.dokka", name = "kotlin-as-java-plugin", version.ref = "dokka"}
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
malefix = { group = "xyz.malefic.frc", name = "malefix", version.ref = "malefix" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
gradleRIO = { id = "edu.wpi.first.GradleRIO", version.ref = "gradleRIO" }
